### ISSUE TITLE
use with volatile varibles inside interrupts 

### ISSUE THREAD

**Issue by waspinator** [dnrce/Spark-PID#1]
Would overloading the PID function with `volatile* doubles ` allow this library to be used inside interrupt functions?

**Comment by dnrce** [comment]
Possibly -- may I suggest you bring this up in the [upstream](https://github.com/br3ttb/Arduino-PID-Library) repo or the Arduino forum? This repo contains only the minimal changes needed to make the upstream project Spark compatible.
